server:
  servlet:
    context-path: /EmployeePortalWithSecurity
spring:
  datasource:
    url: jdbc:mysql://localhost/employeeportal
    username: root
    password: guptaNiraj
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
  mail:
    host: smtp.gmail.com
    port: 587
    username: niraj.gupta@metacube.com
    password: skjjpovrcjvnutcd
    properties.mail.smtp:
      auth: true
      starttls.enable: true